import Foundation

/// Installs Code Island hooks into Claude Code's settings.json.
enum HookInstaller {
    static let bridgePath = "~/.code-island/bin/code-island-bridge"
    static let statusLinePath = "~/.code-island/bin/code-island-statusline"

    @discardableResult
    static func install() -> Bool {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let settingsPath = home.appendingPathComponent(".claude/settings.json")

        // Create ~/.claude/ dir if needed
        let claudeDir = home.appendingPathComponent(".claude")
        try? FileManager.default.createDirectory(at: claudeDir, withIntermediateDirectories: true)

        // Read existing settings or create empty
        var settings = readJSON(at: settingsPath) ?? [:]

        // Get or create hooks dict
        var hooks = settings["hooks"] as? [String: Any] ?? [:]

        let hookEvents = [
            "SessionStart", "SessionEnd", "UserPromptSubmit",
            "PreToolUse", "PostToolUse", "Notification",
            "Stop", "SubagentStart", "SubagentStop", "PreCompact",
        ]

        let bridgeCommand = home.path + "/.code-island/bin/code-island-bridge"

        // Permission request needs a long timeout
        let permissionHookEvents = ["PermissionRequest"]

        for event in hookEvents {
            addHookEntry(to: &hooks, event: event, command: bridgeCommand, timeout: nil)
        }
        for event in permissionHookEvents {
            addHookEntry(to: &hooks, event: event, command: bridgeCommand, timeout: 300)
        }

        settings["hooks"] = hooks

        // Note: we used to install a `statusLine` here to cache rate limits
        // from Claude Code's status feed. That's now superseded by the HTTP
        // fetcher in `UsageFetcher`, which works whether Claude is running or
        // not — so we deliberately don't touch the user's statusLine anymore.

        // Write back
        writeJSON(settings, to: settingsPath)

        // Install bridge launcher script
        installBridgeLauncher()

        print("[CodeIsland] Hooks installed successfully")
        return true
    }

    private static func addHookEntry(to hooks: inout [String: Any], event: String, command: String, timeout: Int?) {
        var eventHooks = hooks[event] as? [[String: Any]] ?? []

        // Check if our hook already exists
        let alreadyInstalled = eventHooks.contains { entry in
            guard let entryHooks = entry["hooks"] as? [[String: Any]] else { return false }
            return entryHooks.contains { ($0["command"] as? String)?.contains("code-island") == true }
        }

        guard !alreadyInstalled else { return }

        var hookDef: [String: Any] = [
            "type": "command",
            "command": command,
        ]
        if let timeout {
            hookDef["timeout"] = timeout
        }

        var entry: [String: Any] = ["hooks": [hookDef]]
        if event != "SessionStart" && event != "SessionEnd" && event != "PreCompact" {
            entry["matcher"] = "*"
        }

        eventHooks.append(entry)
        hooks[event] = eventHooks
    }

    private static func installBridgeLauncher() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let binDir = home.appendingPathComponent(".code-island/bin")
        try? FileManager.default.createDirectory(at: binDir, withIntermediateDirectories: true)
        let bridgePath = binDir.appendingPathComponent("code-island-bridge")

        let script = [
            "#!/bin/zsh",
            "# code-island-bridge launcher (auto-generated by Code Island)",
            "H=/Contents/Helpers/CodeIslandBridge",
            "for P in \"/Applications/Code Island.app\" \"$HOME/Applications/Code Island.app\"; do",
            "  B=\"${P}${H}\"; [ -x \"$B\" ] && exec \"$B\" \"$@\"",
            "done",
            "D=\"$HOME/Projects/code-island/.build/release/CodeIslandBridge\"",
            "[ -x \"$D\" ] && exec \"$D\" \"$@\"",
            "D=\"$HOME/Projects/code-island/.build/debug/CodeIslandBridge\"",
            "[ -x \"$D\" ] && exec \"$D\" \"$@\"",
            "echo \"code-island-bridge: app not found.\" >&2",
            "exit 127",
        ].joined(separator: "\n")

        try? script.write(to: bridgePath, atomically: true, encoding: .utf8)

        // Make executable
        var attrs = try? FileManager.default.attributesOfItem(atPath: bridgePath.path)
        attrs?[.posixPermissions] = 0o755
        try? FileManager.default.setAttributes(attrs ?? [.posixPermissions: 0o755], ofItemAtPath: bridgePath.path)
    }

    private static func installStatusLine() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let binDir = home.appendingPathComponent(".code-island/bin")
        try? FileManager.default.createDirectory(at: binDir, withIntermediateDirectories: true)
        let path = binDir.appendingPathComponent("code-island-statusline")

        let script = """
        #!/bin/bash
        # Claude Code StatusLine Script
        # Auto-configured by Code Island
        input=$(cat)

        # Cache rate limits
        _rl=$(echo "$input" | jq -c '.rate_limits // empty' 2>/dev/null)
        [ -n "$_rl" ] && echo "$_rl" > "\(home.path)/.code-island/cache/rl.json"
        """

        try? script.write(to: path, atomically: true, encoding: .utf8)
        try? FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: path.path)
    }

    // MARK: - JSON Helpers

    private static func readJSON(at url: URL) -> [String: Any]? {
        guard let data = try? Data(contentsOf: url),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return nil
        }
        return json
    }

    private static func writeJSON(_ json: [String: Any], to url: URL) {
        guard let data = try? JSONSerialization.data(withJSONObject: json, options: [.prettyPrinted, .sortedKeys]) else {
            return
        }
        try? data.write(to: url, options: .atomic)
    }
}
